# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 1, 12, 12, 40, 4, 171736, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
