# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_project_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(max_length=25),
        ),
    ]
