# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-13 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='average',
        ),
    ]
